# https://micronaut-projects.github.io/micronaut-data/latest/guide/configurationreference.html
micronaut:
  application:
    name: guapodog
<<<<<<< Updated upstream
  server:
      port: 8085
=======
  data:
    pageable:
      default-page-size: 10
      sort-ignore-case: true
      size-parameter-name: pageSize
      sort-delimiter: ":"
>>>>>>> Stashed changes

# Persistence
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true

<<<<<<< Updated upstream
# App Configs
application:
  page: 1
  pageSize: 50
=======
# # App Configs
# application:
#   pageSize: 50
>>>>>>> Stashed changes
